//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Server.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quran.Server.Application.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جز باید بین 1 تا 30 باشد.
        /// </summary>
        internal static string Quran_JozMustBetween {
            get {
                return ResourceManager.GetString("Quran.JozMustBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار صفحه پایانی در صورت تنظیم باید از مقدار شروع بزرگتر مساوی باشد.
        /// </summary>
        internal static string Quran_LastPageIfSetMustBeGreaterThanStartPage {
            get {
                return ResourceManager.GetString("Quran.LastPageIfSetMustBeGreaterThanStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار صفحه شروع از یک شروع می شود.
        /// </summary>
        internal static string Quran_PageMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Quran.PageMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حزب باید بین 1 تا 240 باشد.
        /// </summary>
        internal static string Quran_RubMustBetween {
            get {
                return ResourceManager.GetString("Quran.RubMustBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پایان صفحه بعد از پایان سوره است.
        /// </summary>
        internal static string Quran_SurahFinishPageLessThanEndPage {
            get {
                return ResourceManager.GetString("Quran.SurahFinishPageLessThanEndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شروع صفحه بعد از پایان سوره است.
        /// </summary>
        internal static string Quran_SurahFinishPageLessThanStartPage {
            get {
                return ResourceManager.GetString("Quran.SurahFinishPageLessThanStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوره پیدا نشد.
        /// </summary>
        internal static string Quran_SurahNotFount {
            get {
                return ResourceManager.GetString("Quran.SurahNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پایان صفحه قبل از شروع سوره است.
        /// </summary>
        internal static string Quran_SurahStartPageGreaterThanEndPage {
            get {
                return ResourceManager.GetString("Quran.SurahStartPageGreaterThanEndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شروع صفحه قبل از شروع سوره است.
        /// </summary>
        internal static string Quran_SurahStartPageGreaterThanStartPage {
            get {
                return ResourceManager.GetString("Quran.SurahStartPageGreaterThanStartPage", resourceCulture);
            }
        }
    }
}
