name: joqds_quran
description: Joqds Quran App for dividing quran between peoples

publish_to: 'none'
version: 0.0.1+0

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  chopper: ^4.0.1
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  convex_bottom_bar: ^3.0.0
  fluent_appbar: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.0
  chopper_generator: ^4.0.1
  json_annotation: ^4.0.1
  json_serializable: ^4.1.4
  swagger_dart_code_generator: 2.0.8
  flutter_launcher_icons: "^0.9.1"
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/